### ISSUE TITLE
Feature Request: Process of LSP

### ISSUE THREAD

**Issue by TornaxO7** [spywhere/lightline-lsp#3]
Hi! Thank you for creating this plugin!

Is it possible that you expand this plugin by creating another function which shows something like a loading circle + loading information of the given LSP? Like showing the status of the LSP what it's doing. That would be pretty neat because I don't know how to implement that with `lsp-status`.
[Here](https://github.com/nvim-lua/lsp-status.nvim/blob/master/images/msgs.png)'s an example how it should look like from the README.md of `lsp-status`.

**Comment by spywhere** [comment]
Hi, thanks for the suggestion. That's look very useful to me. Though since I'm not using lightline anymore, may I know why can't simply use `lsp-status` directly in lightline? Since on the `lsp-status` they already provided an API function for getting the status component, this should be pretty straightforward to set it up.

**Comment by spywhere** [comment]
Moreover, the progress report seems to be available to a limited number of language servers. This would means maintaining various language servers in order to have those progress works.

**Comment by TornaxO7** [comment]
> Though since I'm not using lightline anymore, may I know why can't simply use lsp-status directly in lightline? 

Well... I'm a little bit too stupid to understand how to do this...

This are my settings at the moment:

<details>

```vim
lua require('lsp-status').register_progress()

let g:lightline = {
            \  ...
            \   'right': [ [ 'lineinfo', 'percent' ],
            \              [ 'filetype' ],
            \              [ 'lsp_progress', 'fileformat', 'fileencoding', 'charvaluehex '],
            \  ...
            \ 'component_expand' : {
            \     'my_readonly' : 'LightlineReadonly',
            \     'lsp_progress' : 'LSPProgress',
            \   },
            \ }

function LSPProgress()
    return lua requir('lsp-status').messages()
endfunction
```

</details>

But this doesn't seem to work. I don't get this nice loading-circle in the right part of my lightline-config. Do you have an idea how I can fix this?

**Comment by spywhere** [comment]
Your `LSPProgress` function have a typo of `requir` -> `require`. Also, under [Usage section](https://github.com/nvim-lua/lsp-status.nvim#usage) of lsp-status, you would need `status()` function not `messages()` function. And I'm not sure if you would need to put that under `component_function` rather than `component_expand`.

**Comment by TornaxO7** [comment]
Thank you for these hints!
My config looks like this now:

```vim
lua require('lsp-status').register_progress()

let g:lightline = {
            \  ...
            \   'right': [ [ 'lineinfo', 'percent' ],
            \              [ 'filetype' ],
            \              [ 'lsp_progress', 'fileformat', 'fileencoding', 'charvaluehex '],
            \  ...
               \ 'component_function' : {
            \     'my_modified' : 'LightlineModified',
            \     'gitbranch' : 'FugitiveHead',
            \     'word_counter' : 'WordCounter',
            \     'lsp_progress' : 'LSPProgress',
            \   },
            \ ...
            \}

function LSPProgress()
    lua return require('lsp-status').status()
endfunction
```

but I'm just seeing a `0` in my statusline.

**Comment by spywhere** [comment]
Your `LSPProgress` function is just a call to lua script to return something but it doesn't return anything back from it. You might need to look into `:h luaeval` for more information on how to pass a value from lua script to vimscript. The rest seems good to me. I think this is more or less just a configuration to make it work now, not the possibility of having it working. So I'll close this issue here.
